
services:
  frontend-admin-nuxt:
    build: .
    container_name: frontend-admin-nuxt
    ports:
      - '9020:9020'
    volumes:
      - .:/home/node/app:rw
    restart: 'no'
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true