version: '3'

services:
  app-backend-nginx:
    image: nginx:latest
    restart: always
    tty: true
    depends_on:
      - php
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    links:
      - php

  php:
    container_name: app-backend-php
    build:
      context: ./docker
    restart: always
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - ./:/var/www/html
      - /dev/shm:/dev/shm

  app-backend-mysql:
    container_name: app-backend-mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE:-database_dev}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
    tty: true
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - 3310:3306
    expose:
      - 3310

  app-backend-phpmyadmin:
    container_name: app-backend-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST:-app-backend-mysql}
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - 8097:80

  app-backend-redis:
    image: redis:6.0
    restart: unless-stopped
    ports:
      - 6394:6379

volumes:
  data-mysql: { }
